### ISSUE TITLE
Docker In docker volume mount problem

### ISSUE THREAD

**Issue by pradeepvishwakarma** [RobertoPrevato/AzureDevOps-agents#18]
Hello, I tried the docker-in-docker image from the given set of configuration and I'm able to successfully start agent.

But when we ran another container inside the agent container, we faced volume related issues. As the current setup is starting the child container as a sibling instead of proper child. This is just because of shared docker daemon.

So there are two problem here,

1) the work directory
2) the tool directory

*If we share the work directory from host then the tool directory as well used from host directory.
*Even if we share work directory with agent. we have to create same directory structure in host to map it with internal structure of container.

Could you please advise how should I setup the agent and internal containers independent of host volume.

**Comment by RobertoPrevato** [comment]
Hi @pradeepvishwakarma,
As far as I know, when you run Docker inside Docker, in the running container you have only the client. When you run docker commands you can only run commands as siblings. I wouldn't try to share the work directory between agents.

Therefore the "docker inside docker" container is good to run jobs that require docker, such as building images and pushing them to registries. But it doesn't enable sharing the work tool among different agents to, for example, save bandwidth.

At work we've been using these machines for months: each running agent in its own Docker container has its own set of tools.

**Comment by pradeepvishwakarma** [comment]
Thanks for your advice and help :+1:
